version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
  api:
    build: .
    environment:
      MYSQL_HOST: mysql
    env_file:
      - .env
    ports:
      - "8000:8000"